// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://berdddydopodszrqoeli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcmRkZHlkb3BvZHN6cnFvZWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTg0OTcsImV4cCI6MjA2NTE5NDQ5N30.57WWa2dWeYf0aYrkpKkWEgyejY8maco5uguWiuK6uf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);